name: $(versionSemantic)

trigger: none
# trigger:
#   branches:
#     include:
#       - master
#       - develop
#       - feature/*
#       - release/*
#       - hotfix/*

pool:
  name: Cloud Pool
  demands:
   - maven

parameters:
  - name: jFrogArtifactoryRepoName
    type: string
    default: "libs-snapshot"
    
  - name: artifactoryServiceConnectionName
    type: string
    default: 'Artifactory-PROD'

resources:
  repositories:
    - repository: azure-pipeline-yaml-templates
      type: git
      name: Cloud Team/azure-pipeline-yaml-templates
      ref: feature/sre-md-report
      #ref: disputes-tas


extends:
  template: products/tas/sre/sre-tas-md.yml@azure-pipeline-yaml-templates
  parameters:
  #### Common controls
    #artifactsUpload: AzureArtifacts
    artifactsUpload: Artifactory
    binArtifactSource: 'cloud-sre-logging-framework/target'
    cfManifestSource: $(Build.SourcesDirectory)
    mvnArtifactToUpload: 'sre-common-logging-framework*.jar'
    mvnArtifactCopyTargetFolder: 'cicdmd/dist/target'
    #mvnCfArtifactToUpload: manifest.yml
    #mvnCfArtifactCopyTargetFolder: cicdmd/dist
    azureArtifactPathToArchive: cicdmd
    jFrogArtifactoryRepoName: ${{parameters.jFrogArtifactoryRepoName}}
    artifactoryServiceConnectionName: ${{parameters.artifactoryServiceConnectionName}}
#### Audit Trail
    auditTrail: true
#### Gating
#### Checkmarx ####
    checkmarxEnabled: true
    cxfolderExclusion: 'azure-pipeline-yaml-templates,cloud-sre-observability/cloud-sre-aac-templates,cloud-sre-observability/cloud-sre-dashboard,cloud-sre-observability/cloud-sre-iac-templates,cloud-sre-observability/cloud-sre-mac-templates,instrumentation-library'
#### Blackduck ####
    blackduckEnabled: true
    bdfolderExclusion: 'azure-pipeline-yaml-templates,cloud-sre-aac-templates,cloud-sre-dashboard,cloud-sre-iac-templates,cloud-sre-mac-templates,instrumentation-library'
    blackduckExtraArgs: "--detect.source.path='$(Build.SourcesDirectory)/cloud-sre-logging-framework/target'"
#### Sonarqube ####
    sonarqubeEnabled: true
#### SonarQube qualitygate used for reporting
    #sonarqubeQualityGate: 'Modern Deployment Quality Gate - Baseline'
    sonarqubeProjectKey: org.nfcu.sre.clf:sre-common-logging-framework
    sonarqubeBranchName: feature/logging-framework
    sonarfolderExclusion: 'azure-pipeline-yaml-templates/**,cloud-sre-observability/cloud-sre-aac-templates/**,cloud-sre-observability/cloud-sre-dashboard/**,cloud-sre-observability/cloud-sre-iac-templates/**,cloud-sre-observability/cloud-sre-mac-templates/**,instrumentation-library/**'
#### Build  
    buildType: Maven
    appType: Others
    trunkBranches:
      - refs/heads/master
      - refs/heads/develop
      - refs/heads/feature
    versionMajor: 1
    versionMinor: 0
    buildArgs:
    - name: mavenArgs
      jdkVersion: 11
      pomFile: cloud-sre-logging-framework/pom.xml
      mavenOptions: '-DincPatch,-Dmaven.test.skip=false'
    #--deploy
    deploy: false  
    sso: SKIP
    credhub: SKIP
    isFirstTimeDeploying: false
